from PyQt5 import QtCore, QtGui, QtWidgets
""""
Este script contiene la clase principal y padre de todo el diseño grafico de la interfaz en su 
apartado principal, por ello este script es practicamente infuncional en este estado debido a que 
todo los botones, paginas, etiquedas y demas widgets no tienen asignado un evento especifico.
Cabe destacar que dichos eventos de funcionalidad se desarrollan el script Funciones_Menu_principal.
"""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 602)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setStyleSheet("background: qradialgradient(spread:pad, cx:0.506, cy:0.506, radius:0.5, fx:0.511, fy:0.511, stop:0 rgba(0, 42, 86, 255), stop:0.306818 rgba(0, 31, 65, 255), stop:0.625 rgba(0, 31, 65, 255), stop:1 rgba(0, 22, 45, 255));\n"
"border:none\n"
"QPush\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget.setStyleSheet("QLineEdit{\n"
"background:transparent; \n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"font-size:18px; \n"
"background:transparent; \n"
"}\n"
"QPushButton{\n"
"font-family: calibri;\n"
"background:transparent;\n"
"color: white;\n"
"text-transform: uppercase;\n"
"text-decoration:none;\n"
"font-size:12px;\n"
"font-family: century gothic;\n"
"font-family: Segoe UI;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"color: white;\n"
"border-bottom:1px solid white;\n"
"font-weigth:bold;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frm_top_bar = QtWidgets.QFrame(self.centralwidget)
        self.frm_top_bar.setMinimumSize(QtCore.QSize(0, 45))
        self.frm_top_bar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frm_top_bar.setStyleSheet("background: rgb(29, 31, 42)\n"
"")
        self.frm_top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_top_bar.setObjectName("frm_top_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_top_bar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frm_top_bar)
        self.frame.setMinimumSize(QtCore.QSize(130, 0))
        self.frame.setMaximumSize(QtCore.QSize(130, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frm_btn_principales = QtWidgets.QFrame(self.frm_top_bar)
        self.frm_btn_principales.setMinimumSize(QtCore.QSize(415, 0))
        self.frm_btn_principales.setMaximumSize(QtCore.QSize(415, 16777215))
        self.frm_btn_principales.setStyleSheet("font-size:15px")
        self.frm_btn_principales.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_btn_principales.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_btn_principales.setObjectName("frm_btn_principales")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_btn_principales)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_inicio_inicio = QtWidgets.QPushButton(self.frm_btn_principales)
        self.btn_inicio_inicio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_inicio_inicio.setStyleSheet("font-size:15px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icon_inicio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio_inicio.setIcon(icon)
        self.btn_inicio_inicio.setCheckable(True)
        self.btn_inicio_inicio.setChecked(True)
        self.btn_inicio_inicio.setObjectName("btn_inicio_inicio")
        self.horizontalLayout_3.addWidget(self.btn_inicio_inicio)
        self.btn_inicio_peliculas = QtWidgets.QPushButton(self.frm_btn_principales)
        self.btn_inicio_peliculas.setMinimumSize(QtCore.QSize(95, 20))
        self.btn_inicio_peliculas.setMaximumSize(QtCore.QSize(95, 16777215))
        self.btn_inicio_peliculas.setStyleSheet("font-size:15px; \n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icon_Film.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio_peliculas.setIcon(icon1)
        self.btn_inicio_peliculas.setCheckable(True)
        self.btn_inicio_peliculas.setChecked(True)
        self.btn_inicio_peliculas.setObjectName("btn_inicio_peliculas")
        self.horizontalLayout_3.addWidget(self.btn_inicio_peliculas)
        self.btn_inicio_canales = QtWidgets.QPushButton(self.frm_btn_principales)
        self.btn_inicio_canales.setMaximumSize(QtCore.QSize(90, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icon_tv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio_canales.setIcon(icon2)
        self.btn_inicio_canales.setCheckable(True)
        self.btn_inicio_canales.setChecked(True)
        self.btn_inicio_canales.setObjectName("btn_inicio_canales")
        self.horizontalLayout_3.addWidget(self.btn_inicio_canales)
        self.horizontalLayout_4.addWidget(self.frm_btn_principales)
        self.frame_2 = QtWidgets.QFrame(self.frm_top_bar)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.frm_search_inicial = QtWidgets.QFrame(self.frm_top_bar)
        self.frm_search_inicial.setMinimumSize(QtCore.QSize(250, 30))
        self.frm_search_inicial.setMaximumSize(QtCore.QSize(250, 30))
        self.frm_search_inicial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_search_inicial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_search_inicial.setObjectName("frm_search_inicial")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_search_inicial)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_buscar_inicial = QtWidgets.QLineEdit(self.frm_search_inicial)
        self.txt_buscar_inicial.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_buscar_inicial.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txt_buscar_inicial.setStyleSheet("color: white\n"
"")
        self.txt_buscar_inicial.setText("")
        self.txt_buscar_inicial.setObjectName("txt_buscar_inicial")
        self.horizontalLayout.addWidget(self.txt_buscar_inicial)
        self.btn_search_inicial = QtWidgets.QPushButton(self.frm_search_inicial)
        self.btn_search_inicial.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_search_inicial.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_search_inicial.setStyleSheet("background:transparent;\n"
"border:none\n"
"")
        self.btn_search_inicial.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icon_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search_inicial.setIcon(icon3)
        self.btn_search_inicial.setIconSize(QtCore.QSize(20, 20))
        self.btn_search_inicial.setObjectName("btn_search_inicial")
        self.horizontalLayout.addWidget(self.btn_search_inicial)
        self.horizontalLayout_4.addWidget(self.frm_search_inicial)
        self.verticalLayout.addWidget(self.frm_top_bar)
        self.frm_principal = QtWidgets.QFrame(self.centralwidget)
        self.frm_principal.setStyleSheet("background: rgb(4, 7, 20)")
        self.frm_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_principal.setObjectName("frm_principal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_principal)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frm_paginas = QtWidgets.QFrame(self.frm_principal)
        self.frm_paginas.setStyleSheet("")
        self.frm_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_paginas.setObjectName("frm_paginas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_paginas)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pg_peliculas = QtWidgets.QStackedWidget(self.frm_paginas)
        self.pg_peliculas.setObjectName("pg_peliculas")
        self.pg_inicial = QtWidgets.QWidget()
        self.pg_inicial.setStyleSheet("")
        self.pg_inicial.setObjectName("pg_inicial")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pg_inicial)
        self.verticalLayout_3.setContentsMargins(0, 25, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_ini_1 = QtWidgets.QFrame(self.pg_inicial)
        self.frame_ini_1.setMaximumSize(QtCore.QSize(16777215, 189))
        self.frame_ini_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ini_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ini_1.setObjectName("frame_ini_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_ini_1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spacer = QtWidgets.QFrame(self.frame_ini_1)
        self.spacer.setMinimumSize(QtCore.QSize(31, 0))
        self.spacer.setMaximumSize(QtCore.QSize(16777215, 189))
        self.spacer.setStyleSheet("")
        self.spacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer.setObjectName("spacer")
        self.horizontalLayout_6.addWidget(self.spacer)
        self.frm_slide = QtWidgets.QFrame(self.frame_ini_1)
        self.frm_slide.setMinimumSize(QtCore.QSize(849, 200))
        self.frm_slide.setMaximumSize(QtCore.QSize(860, 200))
        self.frm_slide.setStyleSheet("")
        self.frm_slide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_slide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_slide.setObjectName("frm_slide")
        self.frame_slide_imagen = QtWidgets.QFrame(self.frm_slide)
        self.frame_slide_imagen.setGeometry(QtCore.QRect(0, 0, 840, 189))
        self.frame_slide_imagen.setStyleSheet("")
        self.frame_slide_imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slide_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slide_imagen.setObjectName("frame_slide_imagen")
        self.frm_slide_imagen_slider_1 = QtWidgets.QFrame(self.frame_slide_imagen)
        self.frm_slide_imagen_slider_1.setGeometry(QtCore.QRect(0, 0, 840, 189))
        self.frm_slide_imagen_slider_1.setStyleSheet("filter: blur(6px);")
        self.frm_slide_imagen_slider_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_slide_imagen_slider_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_slide_imagen_slider_1.setObjectName("frm_slide_imagen_slider_1")
        self.frm_slide_imagen_slider_2 = QtWidgets.QFrame(self.frame_slide_imagen)
        self.frm_slide_imagen_slider_2.setGeometry(QtCore.QRect(840, 0, 840, 189))
        self.frm_slide_imagen_slider_2.setStyleSheet("background:rgb(255, 170, 127)")
        self.frm_slide_imagen_slider_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_slide_imagen_slider_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_slide_imagen_slider_2.setObjectName("frm_slide_imagen_slider_2")
        self.frm_slide_imagen_slider_3 = QtWidgets.QFrame(self.frame_slide_imagen)
        self.frm_slide_imagen_slider_3.setGeometry(QtCore.QRect(-840, 0, 840, 189))
        self.frm_slide_imagen_slider_3.setStyleSheet("background:rgb(255, 170, 127)")
        self.frm_slide_imagen_slider_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_slide_imagen_slider_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_slide_imagen_slider_3.setObjectName("frm_slide_imagen_slider_3")
        self.btn_slide_frame = QtWidgets.QPushButton(self.frame_slide_imagen)
        self.btn_slide_frame.setGeometry(QtCore.QRect(50, 10, 751, 161))
        self.btn_slide_frame.setStyleSheet("border:none;\n"
"background: transparent")
        self.btn_slide_frame.setText("")
        self.btn_slide_frame.setObjectName("btn_slide_frame")
        self.btn_slider_anterior = QtWidgets.QPushButton(self.frm_slide)
        self.btn_slider_anterior.setGeometry(QtCore.QRect(0, 70, 32, 32))
        self.btn_slider_anterior.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_slider_anterior.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_slider_anterior.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icon_arrow_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_slider_anterior.setIcon(icon4)
        self.btn_slider_anterior.setIconSize(QtCore.QSize(32, 32))
        self.btn_slider_anterior.setObjectName("btn_slider_anterior")
        self.btn_slider_siguiente = QtWidgets.QPushButton(self.frm_slide)
        self.btn_slider_siguiente.setGeometry(QtCore.QRect(810, 70, 32, 32))
        self.btn_slider_siguiente.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_slider_siguiente.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_slider_siguiente.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icon_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_slider_siguiente.setIcon(icon5)
        self.btn_slider_siguiente.setIconSize(QtCore.QSize(32, 32))
        self.btn_slider_siguiente.setObjectName("btn_slider_siguiente")
        self.frame_slide_imagen.raise_()
        self.btn_slider_siguiente.raise_()
        self.btn_slider_anterior.raise_()
        self.horizontalLayout_6.addWidget(self.frm_slide)
        self.spacer_1 = QtWidgets.QFrame(self.frame_ini_1)
        self.spacer_1.setMaximumSize(QtCore.QSize(16777215, 189))
        self.spacer_1.setStyleSheet("")
        self.spacer_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spacer_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spacer_1.setObjectName("spacer_1")
        self.horizontalLayout_6.addWidget(self.spacer_1)
        self.verticalLayout_3.addWidget(self.frame_ini_1)
        self.frm_pg_inicial_2 = QtWidgets.QFrame(self.pg_inicial)
        self.frm_pg_inicial_2.setStyleSheet("")
        self.frm_pg_inicial_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_pg_inicial_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_pg_inicial_2.setObjectName("frm_pg_inicial_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_pg_inicial_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frm_lbl_favoritos = QtWidgets.QFrame(self.frm_pg_inicial_2)
        self.frm_lbl_favoritos.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frm_lbl_favoritos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_lbl_favoritos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_lbl_favoritos.setObjectName("frm_lbl_favoritos")
        self.btn_inicio_favoritos = QtWidgets.QPushButton(self.frm_lbl_favoritos)
        self.btn_inicio_favoritos.setGeometry(QtCore.QRect(10, 10, 135, 20))
        self.btn_inicio_favoritos.setMinimumSize(QtCore.QSize(135, 0))
        self.btn_inicio_favoritos.setMaximumSize(QtCore.QSize(135, 16777215))
        self.btn_inicio_favoritos.setStyleSheet("font-size:15px")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icon_favoritos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio_favoritos.setIcon(icon6)
        self.btn_inicio_favoritos.setCheckable(True)
        self.btn_inicio_favoritos.setObjectName("btn_inicio_favoritos")
        self.verticalLayout_4.addWidget(self.frm_lbl_favoritos)
        self.frm_btn_fav = QtWidgets.QFrame(self.frm_pg_inicial_2)
        self.frm_btn_fav.setStyleSheet("")
        self.frm_btn_fav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_btn_fav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_btn_fav.setObjectName("frm_btn_fav")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_btn_fav)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frm_conten_btn_favs = QtWidgets.QFrame(self.frm_btn_fav)
        self.frm_conten_btn_favs.setMinimumSize(QtCore.QSize(892, 100))
        self.frm_conten_btn_favs.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frm_conten_btn_favs.setStyleSheet("")
        self.frm_conten_btn_favs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_conten_btn_favs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_conten_btn_favs.setObjectName("frm_conten_btn_favs")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frm_conten_btn_favs)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_fav_1 = QtWidgets.QPushButton(self.frm_conten_btn_favs)
        self.btn_fav_1.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_fav_1.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_fav_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icon_fox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fav_1.setIcon(icon7)
        self.btn_fav_1.setIconSize(QtCore.QSize(130, 130))
        self.btn_fav_1.setObjectName("btn_fav_1")
        self.horizontalLayout_7.addWidget(self.btn_fav_1)
        self.btn_fav_2 = QtWidgets.QPushButton(self.frm_conten_btn_favs)
        self.btn_fav_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_fav_2.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_fav_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icon_cartoon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fav_2.setIcon(icon8)
        self.btn_fav_2.setIconSize(QtCore.QSize(150, 150))
        self.btn_fav_2.setObjectName("btn_fav_2")
        self.horizontalLayout_7.addWidget(self.btn_fav_2)
        self.btn_fav_3 = QtWidgets.QPushButton(self.frm_conten_btn_favs)
        self.btn_fav_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_fav_3.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_fav_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icon_rcn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fav_3.setIcon(icon9)
        self.btn_fav_3.setIconSize(QtCore.QSize(150, 150))
        self.btn_fav_3.setObjectName("btn_fav_3")
        self.horizontalLayout_7.addWidget(self.btn_fav_3)
        self.btn_fav_4 = QtWidgets.QPushButton(self.frm_conten_btn_favs)
        self.btn_fav_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_fav_4.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_fav_4.setText("")
        self.btn_fav_4.setIcon(icon9)
        self.btn_fav_4.setIconSize(QtCore.QSize(150, 150))
        self.btn_fav_4.setObjectName("btn_fav_4")
        self.horizontalLayout_7.addWidget(self.btn_fav_4)
        self.verticalLayout_5.addWidget(self.frm_conten_btn_favs)
        self.frame_program_favs = QtWidgets.QFrame(self.frm_btn_fav)
        self.frame_program_favs.setStyleSheet("background: rgb(170, 85, 0)")
        self.frame_program_favs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_program_favs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_program_favs.setObjectName("frame_program_favs")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_program_favs)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frm_program_favs_1 = QtWidgets.QFrame(self.frame_program_favs)
        self.frm_program_favs_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_program_favs_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_program_favs_1.setObjectName("frm_program_favs_1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frm_program_favs_1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_prog_fav_1 = QtWidgets.QPushButton(self.frm_program_favs_1)
        self.btn_prog_fav_1.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_1.setObjectName("btn_prog_fav_1")
        self.horizontalLayout_8.addWidget(self.btn_prog_fav_1)
        self.btn_prog_fav_2 = QtWidgets.QPushButton(self.frm_program_favs_1)
        self.btn_prog_fav_2.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_2.setObjectName("btn_prog_fav_2")
        self.horizontalLayout_8.addWidget(self.btn_prog_fav_2)
        self.btn_prog_fav_3 = QtWidgets.QPushButton(self.frm_program_favs_1)
        self.btn_prog_fav_3.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_3.setObjectName("btn_prog_fav_3")
        self.horizontalLayout_8.addWidget(self.btn_prog_fav_3)
        self.btn_prog_fav_4 = QtWidgets.QPushButton(self.frm_program_favs_1)
        self.btn_prog_fav_4.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_4.setObjectName("btn_prog_fav_4")
        self.horizontalLayout_8.addWidget(self.btn_prog_fav_4)
        self.btn_prog_fav_5 = QtWidgets.QPushButton(self.frm_program_favs_1)
        self.btn_prog_fav_5.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_5.setObjectName("btn_prog_fav_5")
        self.horizontalLayout_8.addWidget(self.btn_prog_fav_5)
        self.verticalLayout_6.addWidget(self.frm_program_favs_1)
        self.frm_program_favs_2 = QtWidgets.QFrame(self.frame_program_favs)
        self.frm_program_favs_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frm_program_favs_2.setStyleSheet("background:rgb(85, 255, 127)")
        self.frm_program_favs_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_program_favs_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_program_favs_2.setObjectName("frm_program_favs_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frm_program_favs_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_prog_fav_6 = QtWidgets.QPushButton(self.frm_program_favs_2)
        self.btn_prog_fav_6.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_6.setObjectName("btn_prog_fav_6")
        self.horizontalLayout_9.addWidget(self.btn_prog_fav_6)
        self.btn_prog_fav_7 = QtWidgets.QPushButton(self.frm_program_favs_2)
        self.btn_prog_fav_7.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_7.setObjectName("btn_prog_fav_7")
        self.horizontalLayout_9.addWidget(self.btn_prog_fav_7)
        self.btn_prog_fav_8 = QtWidgets.QPushButton(self.frm_program_favs_2)
        self.btn_prog_fav_8.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_8.setObjectName("btn_prog_fav_8")
        self.horizontalLayout_9.addWidget(self.btn_prog_fav_8)
        self.btn_prog_fav_9 = QtWidgets.QPushButton(self.frm_program_favs_2)
        self.btn_prog_fav_9.setStyleSheet("border:none;\n"
"")
        self.btn_prog_fav_9.setObjectName("btn_prog_fav_9")
        self.horizontalLayout_9.addWidget(self.btn_prog_fav_9)
        self.verticalLayout_6.addWidget(self.frm_program_favs_2)
        self.verticalLayout_5.addWidget(self.frame_program_favs)
        self.verticalLayout_4.addWidget(self.frm_btn_fav)
        self.verticalLayout_3.addWidget(self.frm_pg_inicial_2)
        self.pg_peliculas.addWidget(self.pg_inicial)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_peliculas = QtWidgets.QFrame(self.page)
        self.frame_peliculas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_peliculas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_peliculas.setObjectName("frame_peliculas")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_peliculas)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_4 = QtWidgets.QFrame(self.frame_peliculas)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.verticalLayout_17.addWidget(self.frame_4)
        self.frame_conten_peliculas = QtWidgets.QFrame(self.frame_peliculas)
        self.frame_conten_peliculas.setStyleSheet("")
        self.frame_conten_peliculas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_conten_peliculas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_conten_peliculas.setObjectName("frame_conten_peliculas")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_conten_peliculas)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.conten_peliculas_fil_1 = QtWidgets.QFrame(self.frame_conten_peliculas)
        self.conten_peliculas_fil_1.setStyleSheet("")
        self.conten_peliculas_fil_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conten_peliculas_fil_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conten_peliculas_fil_1.setObjectName("conten_peliculas_fil_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.conten_peliculas_fil_1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_pelicula_2 = QtWidgets.QPushButton(self.conten_peliculas_fil_1)
        self.btn_pelicula_2.setStyleSheet("border:none")
        self.btn_pelicula_2.setObjectName("btn_pelicula_2")
        self.horizontalLayout_12.addWidget(self.btn_pelicula_2)
        self.btn_pelicula_1 = QtWidgets.QPushButton(self.conten_peliculas_fil_1)
        self.btn_pelicula_1.setStyleSheet("border:none")
        self.btn_pelicula_1.setObjectName("btn_pelicula_1")
        self.horizontalLayout_12.addWidget(self.btn_pelicula_1)
        self.btn_pelicula_3 = QtWidgets.QPushButton(self.conten_peliculas_fil_1)
        self.btn_pelicula_3.setStyleSheet("border:none")
        self.btn_pelicula_3.setObjectName("btn_pelicula_3")
        self.horizontalLayout_12.addWidget(self.btn_pelicula_3)
        self.btn_pelicula_4 = QtWidgets.QPushButton(self.conten_peliculas_fil_1)
        self.btn_pelicula_4.setStyleSheet("border:none")
        self.btn_pelicula_4.setObjectName("btn_pelicula_4")
        self.horizontalLayout_12.addWidget(self.btn_pelicula_4)
        self.btn_pelicula_5 = QtWidgets.QPushButton(self.conten_peliculas_fil_1)
        self.btn_pelicula_5.setStyleSheet("border:none")
        self.btn_pelicula_5.setObjectName("btn_pelicula_5")
        self.horizontalLayout_12.addWidget(self.btn_pelicula_5)
        self.verticalLayout_16.addWidget(self.conten_peliculas_fil_1)
        self.conten_peliculas_fil_2 = QtWidgets.QFrame(self.frame_conten_peliculas)
        self.conten_peliculas_fil_2.setStyleSheet("")
        self.conten_peliculas_fil_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conten_peliculas_fil_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conten_peliculas_fil_2.setObjectName("conten_peliculas_fil_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.conten_peliculas_fil_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_pelicula_6 = QtWidgets.QPushButton(self.conten_peliculas_fil_2)
        self.btn_pelicula_6.setStyleSheet("border:none")
        self.btn_pelicula_6.setObjectName("btn_pelicula_6")
        self.horizontalLayout_13.addWidget(self.btn_pelicula_6)
        self.btn_pelicula_7 = QtWidgets.QPushButton(self.conten_peliculas_fil_2)
        self.btn_pelicula_7.setStyleSheet("border:none")
        self.btn_pelicula_7.setObjectName("btn_pelicula_7")
        self.horizontalLayout_13.addWidget(self.btn_pelicula_7)
        self.btn_pelicula_8 = QtWidgets.QPushButton(self.conten_peliculas_fil_2)
        self.btn_pelicula_8.setStyleSheet("border:none")
        self.btn_pelicula_8.setObjectName("btn_pelicula_8")
        self.horizontalLayout_13.addWidget(self.btn_pelicula_8)
        self.btn_pelicula_9 = QtWidgets.QPushButton(self.conten_peliculas_fil_2)
        self.btn_pelicula_9.setStyleSheet("border:none")
        self.btn_pelicula_9.setObjectName("btn_pelicula_9")
        self.horizontalLayout_13.addWidget(self.btn_pelicula_9)
        self.btn_pelicula_10 = QtWidgets.QPushButton(self.conten_peliculas_fil_2)
        self.btn_pelicula_10.setStyleSheet("border:none")
        self.btn_pelicula_10.setObjectName("btn_pelicula_10")
        self.horizontalLayout_13.addWidget(self.btn_pelicula_10)
        self.verticalLayout_16.addWidget(self.conten_peliculas_fil_2)
        self.conten_peliculas_fil_3 = QtWidgets.QFrame(self.frame_conten_peliculas)
        self.conten_peliculas_fil_3.setStyleSheet("")
        self.conten_peliculas_fil_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conten_peliculas_fil_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conten_peliculas_fil_3.setObjectName("conten_peliculas_fil_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.conten_peliculas_fil_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_pelicula_11 = QtWidgets.QPushButton(self.conten_peliculas_fil_3)
        self.btn_pelicula_11.setStyleSheet("border:none")
        self.btn_pelicula_11.setObjectName("btn_pelicula_11")
        self.horizontalLayout_14.addWidget(self.btn_pelicula_11)
        self.btn_pelicula_12 = QtWidgets.QPushButton(self.conten_peliculas_fil_3)
        self.btn_pelicula_12.setStyleSheet("border:none")
        self.btn_pelicula_12.setObjectName("btn_pelicula_12")
        self.horizontalLayout_14.addWidget(self.btn_pelicula_12)
        self.btn_pelicula_13 = QtWidgets.QPushButton(self.conten_peliculas_fil_3)
        self.btn_pelicula_13.setStyleSheet("border:none")
        self.btn_pelicula_13.setObjectName("btn_pelicula_13")
        self.horizontalLayout_14.addWidget(self.btn_pelicula_13)
        self.btn_pelicula_14 = QtWidgets.QPushButton(self.conten_peliculas_fil_3)
        self.btn_pelicula_14.setStyleSheet("border:none")
        self.btn_pelicula_14.setObjectName("btn_pelicula_14")
        self.horizontalLayout_14.addWidget(self.btn_pelicula_14)
        self.btn_pelicula_15 = QtWidgets.QPushButton(self.conten_peliculas_fil_3)
        self.btn_pelicula_15.setStyleSheet("border:none")
        self.btn_pelicula_15.setObjectName("btn_pelicula_15")
        self.horizontalLayout_14.addWidget(self.btn_pelicula_15)
        self.verticalLayout_16.addWidget(self.conten_peliculas_fil_3)
        self.conten_peliculas_fil_4 = QtWidgets.QFrame(self.frame_conten_peliculas)
        self.conten_peliculas_fil_4.setStyleSheet("")
        self.conten_peliculas_fil_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conten_peliculas_fil_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conten_peliculas_fil_4.setObjectName("conten_peliculas_fil_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.conten_peliculas_fil_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_pelicula_16 = QtWidgets.QPushButton(self.conten_peliculas_fil_4)
        self.btn_pelicula_16.setStyleSheet("border:none")
        self.btn_pelicula_16.setObjectName("btn_pelicula_16")
        self.horizontalLayout_15.addWidget(self.btn_pelicula_16)
        self.btn_pelicula_17 = QtWidgets.QPushButton(self.conten_peliculas_fil_4)
        self.btn_pelicula_17.setStyleSheet("border:none")
        self.btn_pelicula_17.setObjectName("btn_pelicula_17")
        self.horizontalLayout_15.addWidget(self.btn_pelicula_17)
        self.btn_pelicula_18 = QtWidgets.QPushButton(self.conten_peliculas_fil_4)
        self.btn_pelicula_18.setStyleSheet("border:none")
        self.btn_pelicula_18.setObjectName("btn_pelicula_18")
        self.horizontalLayout_15.addWidget(self.btn_pelicula_18)
        self.btn_pelicula_19 = QtWidgets.QPushButton(self.conten_peliculas_fil_4)
        self.btn_pelicula_19.setStyleSheet("border:none")
        self.btn_pelicula_19.setObjectName("btn_pelicula_19")
        self.horizontalLayout_15.addWidget(self.btn_pelicula_19)
        self.btn_pelicula_20 = QtWidgets.QPushButton(self.conten_peliculas_fil_4)
        self.btn_pelicula_20.setStyleSheet("border:none")
        self.btn_pelicula_20.setObjectName("btn_pelicula_20")
        self.horizontalLayout_15.addWidget(self.btn_pelicula_20)
        self.verticalLayout_16.addWidget(self.conten_peliculas_fil_4)
        self.verticalLayout_17.addWidget(self.frame_conten_peliculas)
        self.verticalLayout_14.addWidget(self.frame_peliculas)
        self.pg_peliculas.addWidget(self.page)
        self.pg_canales = QtWidgets.QWidget()
        self.pg_canales.setObjectName("pg_canales")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_canales)
        self.verticalLayout_7.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frm_canales = QtWidgets.QFrame(self.pg_canales)
        self.frm_canales.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_canales.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_canales.setObjectName("frm_canales")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frm_canales)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frm_canales_icons = QtWidgets.QFrame(self.frm_canales)
        self.frm_canales_icons.setMinimumSize(QtCore.QSize(0, 100))
        self.frm_canales_icons.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frm_canales_icons.setStyleSheet("")
        self.frm_canales_icons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_canales_icons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_canales_icons.setObjectName("frm_canales_icons")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frm_canales_icons)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_canal_1 = QtWidgets.QPushButton(self.frm_canales_icons)
        self.btn_canal_1.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_canal_1.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_canal_1.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icon_caracol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_canal_1.setIcon(icon10)
        self.btn_canal_1.setIconSize(QtCore.QSize(130, 130))
        self.btn_canal_1.setObjectName("btn_canal_1")
        self.horizontalLayout_10.addWidget(self.btn_canal_1)
        self.btn_canal_2 = QtWidgets.QPushButton(self.frm_canales_icons)
        self.btn_canal_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_canal_2.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_canal_2.setText("")
        self.btn_canal_2.setIcon(icon8)
        self.btn_canal_2.setIconSize(QtCore.QSize(150, 150))
        self.btn_canal_2.setObjectName("btn_canal_2")
        self.horizontalLayout_10.addWidget(self.btn_canal_2)
        self.btn_canal_3 = QtWidgets.QPushButton(self.frm_canales_icons)
        self.btn_canal_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_canal_3.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_canal_3.setText("")
        self.btn_canal_3.setIcon(icon7)
        self.btn_canal_3.setIconSize(QtCore.QSize(150, 150))
        self.btn_canal_3.setObjectName("btn_canal_3")
        self.horizontalLayout_10.addWidget(self.btn_canal_3)
        self.btn_canal_4 = QtWidgets.QPushButton(self.frm_canales_icons)
        self.btn_canal_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_canal_4.setStyleSheet("border:none;\n"
"background: transparent;")
        self.btn_canal_4.setText("")
        self.btn_canal_4.setIcon(icon9)
        self.btn_canal_4.setIconSize(QtCore.QSize(150, 150))
        self.btn_canal_4.setObjectName("btn_canal_4")
        self.horizontalLayout_10.addWidget(self.btn_canal_4)
        self.verticalLayout_8.addWidget(self.frm_canales_icons)
        self.frm_canales_tabla = QtWidgets.QFrame(self.frm_canales)
        self.frm_canales_tabla.setStyleSheet("")
        self.frm_canales_tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_canales_tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_canales_tabla.setObjectName("frm_canales_tabla")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frm_canales_tabla)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tbl_prograamacion = QtWidgets.QTableWidget(self.frm_canales_tabla)
        self.tbl_prograamacion.setStyleSheet("background-color:transparent;\n"
"color: white;\n"
"QHeaderView{\n"
"Background-color:rgb(255, 85, 0);\n"
" border-radius:14px;}\n"
"\n"
"")
        self.tbl_prograamacion.setObjectName("tbl_prograamacion")
        self.tbl_prograamacion.setColumnCount(3)
        self.tbl_prograamacion.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_prograamacion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_prograamacion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_prograamacion.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.tbl_prograamacion)
        self.verticalLayout_8.addWidget(self.frm_canales_tabla)
        self.verticalLayout_7.addWidget(self.frm_canales)
        self.pg_peliculas.addWidget(self.pg_canales)
        self.pg_busqueda = QtWidgets.QWidget()
        self.pg_busqueda.setObjectName("pg_busqueda")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pg_busqueda)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frm_page_busqueda = QtWidgets.QFrame(self.pg_busqueda)
        self.frm_page_busqueda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_page_busqueda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_page_busqueda.setObjectName("frm_page_busqueda")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frm_page_busqueda)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frm_busqueda_descripcion = QtWidgets.QFrame(self.frm_page_busqueda)
        self.frm_busqueda_descripcion.setMaximumSize(QtCore.QSize(16777215, 108))
        self.frm_busqueda_descripcion.setStyleSheet("")
        self.frm_busqueda_descripcion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_busqueda_descripcion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_busqueda_descripcion.setObjectName("frm_busqueda_descripcion")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frm_busqueda_descripcion)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_busqueda_canal = QtWidgets.QPushButton(self.frm_busqueda_descripcion)
        self.btn_busqueda_canal.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_busqueda_canal.setStyleSheet("border:none")
        self.btn_busqueda_canal.setText("")
        self.btn_busqueda_canal.setIcon(icon10)
        self.btn_busqueda_canal.setIconSize(QtCore.QSize(90, 90))
        self.btn_busqueda_canal.setObjectName("btn_busqueda_canal")
        self.horizontalLayout_11.addWidget(self.btn_busqueda_canal)
        self.frm_busqueda_1 = QtWidgets.QFrame(self.frm_busqueda_descripcion)
        self.frm_busqueda_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_busqueda_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_busqueda_1.setObjectName("frm_busqueda_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frm_busqueda_1)
        self.verticalLayout_11.setContentsMargins(30, 10, 50, 10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_busqueda_dias_emi = QtWidgets.QLabel(self.frm_busqueda_1)
        self.lbl_busqueda_dias_emi.setStyleSheet("font-size:16px; \n"
"color: rgb(235, 235, 235)\n"
"")
        self.lbl_busqueda_dias_emi.setObjectName("lbl_busqueda_dias_emi")
        self.verticalLayout_11.addWidget(self.lbl_busqueda_dias_emi)
        self.lbl_busqueda_horas_emi = QtWidgets.QLabel(self.frm_busqueda_1)
        self.lbl_busqueda_horas_emi.setStyleSheet("font-size:16px; \n"
"color: rgb(235, 235, 235)\n"
"")
        self.lbl_busqueda_horas_emi.setObjectName("lbl_busqueda_horas_emi")
        self.verticalLayout_11.addWidget(self.lbl_busqueda_horas_emi)
        self.lbl_busqueda_canal_emi = QtWidgets.QLabel(self.frm_busqueda_1)
        self.lbl_busqueda_canal_emi.setStyleSheet("color: rgb(255, 255, 255)\n"
"")
        self.lbl_busqueda_canal_emi.setObjectName("lbl_busqueda_canal_emi")
        self.verticalLayout_11.addWidget(self.lbl_busqueda_canal_emi)
        self.horizontalLayout_11.addWidget(self.frm_busqueda_1)
        self.verticalLayout_12.addWidget(self.frm_busqueda_descripcion)
        self.frm_busqueda_descripcion_2 = QtWidgets.QFrame(self.frm_page_busqueda)
        self.frm_busqueda_descripcion_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_busqueda_descripcion_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_busqueda_descripcion_2.setObjectName("frm_busqueda_descripcion_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frm_busqueda_descripcion_2)
        self.verticalLayout_13.setContentsMargins(10, 20, 0, 10)
        self.verticalLayout_13.setSpacing(3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lbl_busqueda_titulo = QtWidgets.QLabel(self.frm_busqueda_descripcion_2)
        self.lbl_busqueda_titulo.setMaximumSize(QtCore.QSize(16777215, 51))
        self.lbl_busqueda_titulo.setStyleSheet("font-size:28px; \n"
"")
        self.lbl_busqueda_titulo.setObjectName("lbl_busqueda_titulo")
        self.verticalLayout_13.addWidget(self.lbl_busqueda_titulo)
        self.lbl_busqueda_tipo = QtWidgets.QLabel(self.frm_busqueda_descripcion_2)
        self.lbl_busqueda_tipo.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_busqueda_tipo.setObjectName("lbl_busqueda_tipo")
        self.verticalLayout_13.addWidget(self.lbl_busqueda_tipo)
        self.lbl_busqueda_sinopsis = QtWidgets.QLabel(self.frm_busqueda_descripcion_2)
        self.lbl_busqueda_sinopsis.setObjectName("lbl_busqueda_sinopsis")
        self.verticalLayout_13.addWidget(self.lbl_busqueda_sinopsis)
        self.verticalLayout_12.addWidget(self.frm_busqueda_descripcion_2)
        self.verticalLayout_10.addWidget(self.frm_page_busqueda)
        self.pg_peliculas.addWidget(self.pg_busqueda)
        self.verticalLayout_2.addWidget(self.pg_peliculas)
        self.horizontalLayout_2.addWidget(self.frm_paginas)
        self.verticalLayout.addWidget(self.frm_principal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pg_peliculas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Py</span><span style=\" font-size:18pt;\">search</span><span style=\" font-size:18pt; font-weight:600;\">!</span></p></body></html>"))
        self.btn_inicio_inicio.setText(_translate("MainWindow", "INICIO"))
        self.btn_inicio_peliculas.setText(_translate("MainWindow", "PELICULAS"))
        self.btn_inicio_canales.setText(_translate("MainWindow", "CANALES"))
        self.txt_buscar_inicial.setPlaceholderText(_translate("MainWindow", "Buscar..."))
        self.btn_inicio_favoritos.setText(_translate("MainWindow", "MIS FAVORITOS"))
        self.btn_prog_fav_1.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_2.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_3.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_4.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_5.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_6.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_7.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_8.setText(_translate("MainWindow", "PushButton"))
        self.btn_prog_fav_9.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Pe</span><span style=\" font-size:28pt;\">liculas</span><span style=\" font-size:28pt; font-weight:600;\">!</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Py</span><span style=\" color:#ffffff;\">search es un sitio ideal para ver y recomendarte peliculas online.</span></p></body></html>"))
        self.btn_pelicula_2.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_1.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_3.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_4.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_5.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_6.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_7.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_8.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_9.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_10.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_11.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_12.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_13.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_14.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_15.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_16.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_17.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_18.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_19.setText(_translate("MainWindow", "Pelicula"))
        self.btn_pelicula_20.setText(_translate("MainWindow", "Pelicula"))
        item = self.tbl_prograamacion.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Programa"))
        item = self.tbl_prograamacion.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dia"))
        item = self.tbl_prograamacion.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hora"))
        self.lbl_busqueda_dias_emi.setText(_translate("MainWindow", "Dias"))
        self.lbl_busqueda_horas_emi.setText(_translate("MainWindow", "Horas"))
        self.lbl_busqueda_canal_emi.setText(_translate("MainWindow", "Canal"))
        self.lbl_busqueda_titulo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">TextLabel</span></p></body></html>"))
        self.lbl_busqueda_tipo.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_busqueda_sinopsis.setText(_translate("MainWindow", "Para salvar a su familia de la ruina, y obligada por su madre, Monserrat debe casarse con Alejandro, un hombre al que no ama y que es dueño de una gran fortuna. Sin embargo, Monserrat está enamorada de otro hombre."))
import Source_image
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
